### ISSUE TITLE
Auth MVP Review

### ISSUE THREAD

**Issue by mmcnulty20** [berthornhill/band-camp-clone#3]
- [x] Navbar Search bar should be aligned where right edge is in line with log in button’s right edge.
- [x] Shrink size of “fans have paid” header and width of albums section under it
- [x] Placement of text within all inputs (placeholder and user input) should be adjusted
- [x] Hover effects on album cards missing
- [x] Shrink footer text, adjust placement of text to more mirror website.
- [x] We’ll talk about the bottom links
- [x] Change “Sign up as Demo User” to “Sign in as…” or similar for clarity
- [x] If you’re going to have the modal for choosing between those (which I like), the styling should match Bandcamps choose-your-account-type modal.
- [x] Spacing between form rows should increase in places, height of inputs should be reduced, size of sign up header and labels should be reduced, labels should not be bold, “Sign up”/“Log in” button at bottom 2 words
- [x] Log out should be dropdown with logout button instead, logged in splash navbar changes size/placement
- [x] Separate errors out beneath their relevant input, change size/font weight, relevant input’s styling (red background/border), clear only error from field changed when typing in that field after getting errors back (not all fields)
- [x] Include “don’t have an account, sign up”/“already have an account? Log in” links at bottom of forms
- [x] At some points received 500 internal error, failing to sign up 
- [x] Do you mean to dispatch a removeErrors action with each change?
 Looking really good so far! :)

**Comment by mmcnulty20** [comment]
- [x] If creating a user with all empty fields, only gets the username and email errors
- [x] got 500 error when making a user when the same band name/email as existing one (no errors display)

If you cannot replicate these errors or they take a notable amount of time to resolve, ask a question via slack and move on until it can be resolved,

**Comment by mmcnulty20** [comment]
- [ ] Add transition to hover effect on album cards
- [ ] Still not getting an error under Artist/Band if created without input
Slacked you about possible additional concern
That said, I'm closing with these still needed as (while I'd recommend you add some version of the first) it's not worth the time to debug the second at the moment. Good work so far! :)

**Comment by berthornhill** [comment]
Thanks Megan. Sorry I misunderstood that you wanted the errors rendering on
the Artist/Band. I had left that intentionally as not having a null
constraint in my DB as I didn't want to force users to also be
bands/artists. I can add those errors. I fixed the resize issue you
mentioned but as far as I can tell, all my album cards/artist cards are
rendering the hover affect. If there's a specific place I'm missing, pelase
let me know so i can make the change. Thanks!
